[credentials]
cred_aws_bucket = "bkt-abc"
cred_aws_key_id = ""
cred_aws_secret = ""
cred_aws_sqs_queue_name = ""
cred_ddh_serial_number = ""
cred_ddh_project_name = ""
cred_aws_custom_sqs_key_id = ""
cred_aws_custom_sqs_access_key = ""

[behavior]
ship_name = "nameofboat"
forget_time = 36000
gear_type = 0
moving_speed = [ 0.5, 7.0,]
fake_gps_position = [ 41.63, -70.91,]

[monitored_macs]
"D0:2E:AB:D9:29:48" = "tdo_bread"

[flags]
aws_en = 1
sqs_en = 1
ble_en = 1
rbl_en = 0
maps_en = 0
sms_en = 0
hook_gps_error_measurement_forced = 0
hook_ble_purge_black_macs_on_boot = 0
hook_ble_purge_this_mac_dl_files_folder = 0
